# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1038878
- name: gambi do java
  apt:
    update_cache: yes
    pkg:
      - ca-certificates-java

- name: pacotes gui
  apt:
    update_cache: yes
    pkg:
      - chromium
      - chromium-l10n
      - default-jre
      - djview4
      - djvulibre-bin
      - elinks
      - fonts-recommended
      - geany
      - gimp
      - hyphen-pt-br
      - info
      - kolourpaint
      - libreoffice-help-pt-br
      - libreoffice-lightproof-pt-br
      - ocsinventory-agent
      - okular
      - pavucontrol
      - pdfarranger
      - python3-tk
      - ttf-mscorefonts-installer
      - unrar-free
      - vlc
      - webext-ublock-origin-chromium
      - webext-ublock-origin-firefox
      - xournal

- name: dconf profile dir
  file:
    path: /etc/dconf/profile
    state: directory

- name: dconf user dbs
  copy:
    src: dconf/user
    dest: /etc/dconf/profile/user

- name: dconf local.d dir
  file:
    path: /etc/dconf/db/local.d
    state: directory

- name: ocs url
  copy:
    content: server=ocs.ime.usp.br
    dest: /etc/ocsinventory/ocsinventory-agent.cfg
