- name: pacotes lab
  apt:
    update_cache: yes
    pkg:
      - kbibtex
      - kile
      - kile-l10n
      - texlive-full
      - texmaker
      - build-essential
      - curl
      - git
      - jq
      - libfontconfig1-dev
      - libfribidi-dev
      - libgdal-dev
      - libgsl-dev
      - libharfbuzz-dev
      - libnode-dev
      - libproj-dev
      - libudunits2-dev
      - libx11-dev
      - octave
      - plink1.9
      - python3-pip
      - spyder
      - x2goclient
      - xfig
      - zstd

- name: logind logout kill
  lineinfile:
    path: /etc/systemd/logind.conf
    line: 'KillUserProcesses=yes'
  notify: reinicia logind

- name: wallpaper
  copy:
    src: wallviso.png
    dest: /usr/share/backgrounds/wallviso.png

- name: configura background
  copy:
    src: dconf/background
    dest: /etc/dconf/db/local.d/00-background
  notify: dconf update

- name: wallpaper login
  copy:
    src: wallogin.png
    dest: /usr/share/backgrounds/wallogin.png

- name: configura login background
  copy:
    src: lightdm-gtk-greeter.conf.d/02_ime.conf
    dest: /usr/share/lightdm/lightdm-gtk-greeter.conf.d/02_ime.conf
