- name: Instala programas usados nas máquinas de sala de aula
  win_chocolatey:
    name:
      - geogebra-classic.install
      - gimp
      - inkscape
      - miktex
      - python
      - r.project
      - r.studio
      - skype
      - texmaker
      - texniccenter
      - zoom
    state: present

- name: Cria usuário audiovisual
  ansible.windows.win_user:
    name: audiovisual
    password: '{{ audiovisual_password }}'
    password_never_expires: yes
    state: present
    groups:
      - 'Administradores'

- name: Cria usuário aula
  ansible.windows.win_user:
    name: aula
    password_never_expires: yes
    state: present
    groups:
      - 'Convidados'

- name: Define o usuário do login automático para o usuário aula
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    type: string
    name: DefaultUserName
    data: aula

- name: Define a senha do login automático para o usuário aula
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    type: string
    name: DefaultPassword
    data: ''

- name: Liga o login automático
  ansible.windows.win_regedit:
    path: 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon'
    type: string
    name: AutoAdminLogon
    data: '1'
